### ISSUE TITLE
Implement the backend logic for getting all the list items

### ISSUE THREAD

**Issue by raubersn** [RussellAbraham/smartTodoApp#13]
Create a function to get all the logged user's TODO items from the database to be shown on the home page.

- The function should receive the logged user's id as a parameter.
- Implement the logic in `~/routes/items.js`
- The database query should be done in `~/db/queries/items.js`. If the file does not exist, create it.

**Comment by raubersn** [comment]
Hi @Olanrewaju-Ak . I believe you will need to have #12 completed before you can do this. You need the user's id from the cookie set when the user logs in to use it as a parameter.

**Comment by Olanrewaju-Ak** [comment]
good catch
